Personal/jamismoy/direct messages feature
HolmanA/cat-chat pull request #78
Opened 2018-12-28 08:12 UTC by jamismoy

First Iteration of direct messages feature. There may be more changes and edits to this branch once the PR is reviewed. A couple of things that I can think of right now. I am not expecting this to be flawless first time around. 

1) Since the selected chats array now contain both direct chats and group chats I had to add some extra logic to check the type as we are iterating over the selected chats array. This is so we know whether to check for chat.id for group chats, or chat.other_user.id for direct chats.

2) Not able to listen for liked received notifications over the direct_message channel. This was an issue at first because the likeRecieved action handler is what toggled the like from "not-liked" to "liked". In order to get around this I toggled the like from the likedDirectMessage action handler. This means that we cannot receive likes in 'real time' from other users for direct messages. You have to close and reopen the direct chat to see the likes that your receive. The like still toggles if the user is the one who likes the message. If this is an issue I can create a task and investigate this issue further. 

3) In direct-messages-list.component.ts I have a two workarounds for these small bugs. Sometimes when you select a group chat it also calls set messagePageList() in the direct-messages-list component, and will error out since the list you are passing it would be undefined. To get around this I just check if the list is undefined or not. (Actually this bug might not exist anymore since I got direct messages into a better state...) Also the messages I received are in reverse order. The issue with calling the reverse() method on the list is that when you load more messages it will reverse everything again so your pages will alternate between reversed and not reversed. To get around this I created a helper method that sorts all the messages by when they were created.

4) To handle picture messages I had to check if the message was null inside the trimMessage() method and assign an empty string if it was. If I didn't do this it would error out and mess up the list of direct chats. I noticed that you didn't have to do this for group messages so I am curious how you handled picture messages. 

5) In the case that we are happy with the functionality BUT have some major refactoring or restructuring to do for whatever reason, I say that we merge this in and create a task to refactor later. Unless its in such a bad state it would be bad practice to merge this in...

Check comments for more explanation.

2018-12-28 08:14 UTC, jamismoy commented on src/app/message-queue-module/store/message-queue.state.ts
> +
Iterating over SelectedChats and checks types to determine wwhere to look for the id

2018-12-28 08:17 UTC, jamismoy commented on src/app/ui-module/direct-messages/components/direct-messages-list/direct-messages-list.component.ts
> +
Helper function to sort the messages by when they were created

2018-12-28 08:18 UTC, jamismoy commented on src/app/ui-module/direct-messages/components/direct-messages-list/direct-messages-list.component.ts
> +        if (list !== undefined) {
Need to check if list is undefined to workaround small bug

2018-12-31 05:46 UTC, jamismoy commented on src/app/ui-module/direct-messages/components/direct-messages-list/direct-messages-list.component.ts
> +        if (list !== undefined) {
removed work around for small bug because because does not exist anymore

2019-01-11 07:16 UTC, jamismoy commented on src/app/message-queue-module/store/message-queue.state.ts
> +                chats[i].type === 'DIRECT' && chats[i].chat.last_message.conversation_id === messageChatId) {
![image](https://user-images.githubusercontent.com/14933876/51018789-b079e180-152d-11e9-9ed7-173fc9b75f23.png)

From the looks of it I don't think so?

2019-01-11 08:38 UTC, jamismoy commented on src/app/message-queue-module/store/message-queue.state.ts
> +    clearGroupMessageQueue({ getState, patchState }: StateContext<MessageQueueStateModel>, action: SelectedChatsStateActions.FetchGroupChatSucceeded) {
Made change in latest commit. 

https://github.com/HolmanA/cat-chat/pull/78/commits/662f3a540f0b4bcd2e90d765ebd0acb798677c15

2019-01-11 08:39 UTC, jamismoy commented on src/app/root-module/services/web-socket/models/direct-channel-configuration.ts
> +        this.subscriptionPath = '/direct_message/' + this.channelId; // '/direct_message/' + this.channelId;
addressed in latest commit https://github.com/HolmanA/cat-chat/pull/78/commits/662f3a540f0b4bcd2e90d765ebd0acb798677c15

2019-01-11 08:40 UTC, jamismoy commented on src/app/selected-chats-module/store/selected-chats.selectors.ts
> +                const chat = state.selectedChats[i]; // .find(c => c.chat.id === chatId);
addressed in latest commit

2019-01-11 08:40 UTC, jamismoy commented on src/app/selected-chats-module/store/selected-chats.selectors.ts
> +import { connectableObservableDescriptor } from 'rxjs/internal/observable/ConnectableObservable';
addressed in latest commit

2019-01-11 08:40 UTC, jamismoy commented on src/app/selected-chats-module/store/selected-chats.state.ts
> +            if (selectedChats[i].type === 'GROUP' && selectedChats[i].chat.id === groupChat.id) {
addressed in latest commit and changed ALL files to use enum https://github.com/HolmanA/cat-chat/pull/78/commits/662f3a540f0b4bcd2e90d765ebd0acb798677c15

2019-01-11 08:42 UTC, jamismoy commented on src/app/selected-chats-module/store/selected-chats.state.ts
> +        const channelId = directChat.last_message.recipient_id + '_' + directChat.last_message.sender_id;
I'm not sure but to handle the case that the channelId will change depending on who sends the message, I just used the conversation ID and replaced the '+' with '_'. Addressed in latest commit 
https://github.com/HolmanA/cat-chat/pull/78/commits/662f3a540f0b4bcd2e90d765ebd0acb798677c15

2019-01-11 08:42 UTC, jamismoy commented on src/app/selected-chats-module/store/selected-chats.state.ts
> +                    type: ChatType.DIRECT,
thanks!

2019-01-11 08:42 UTC, jamismoy commented on src/app/selected-chats-module/store/selected-chats.selectors.ts
> +                const chat = state.selectedChats[i]; // .find(c => c.chat.id === chatId);
addressed in latest commit 
https://github.com/HolmanA/cat-chat/pull/78/commits/662f3a540f0b4bcd2e90d765ebd0acb798677c15

2019-01-11 08:43 UTC, jamismoy commented on src/app/selected-chats-module/actions/selected-chats.actions.ts
> +export class FetchDirectChatsSucceeded {
You are right, they are removed and addressed in latest commit https://github.com/HolmanA/cat-chat/pull/78/commits/662f3a540f0b4bcd2e90d765ebd0acb798677c15

2019-01-11 08:44 UTC, jamismoy commented on src/app/selected-chats-module/store/selected-chats.state.ts
> +        // This section won't do anyting because selectedChats will always clear the selected chat beforehand...
To be honest I am not sure, I think that was a thought that was going through my head at one time. Cannot remember what I was thinking... Comment removed in latest commit https://github.com/HolmanA/cat-chat/pull/78/commits/662f3a540f0b4bcd2e90d765ebd0acb798677c15

2019-01-11 08:45 UTC, jamismoy commented on src/app/selected-chats-module/store/selected-chats.state.ts
> +        // This section won't do anyting because selectedChats will always clear the selected chat beforehand...
I think that was a though I had before I made a change so I cannot remember what I was thinking

2019-01-11 08:46 UTC, jamismoy commented on src/app/selected-chats-module/store/selected-chats.state.ts
> +        let chatIndex = -1;
good suggestion. In next commit i will make these changes to all the places where I am looping over selected chats

2019-01-11 18:40 UTC, HolmanA commented on src/app/message-queue-module/store/message-queue.state.ts
> +                chats[i].type === 'DIRECT' && chats[i].chat.last_message.conversation_id === messageChatId) {
Yup no problem. I was just curious but yeah it looks like they don't include nearly as much information as they do for group chats.

2019-01-11 19:00 UTC, HolmanA commented on src/app/selected-chats-module/store/selected-chats.state.ts
> +        // This section won't do anyting because selectedChats will always clear the selected chat beforehand...
Gotcha no worries

2019-01-13 00:55 UTC, jamismoy commented on src/app/selected-chats-module/store/selected-chats.state.ts
> +        let chatIndex = -1;
addressed in latest commit https://github.com/HolmanA/cat-chat/pull/78/commits/5e21d28fcab22a47910c31db3ac13ef93844d5ff

2019-01-18 18:17 UTC, HolmanA commented on src/app/message-queue-module/store/message-queue.state.ts
> -        const chatOpen = chats.find(chat => chat.chat.id === messageChatId);
[NIT] This could be simplified with the `.find()` method. The find method accepts a function that acts as the condition you are trying to find. Your for loop below could be simplified to: 
```
const chatOpen = chats.find(chat => {
   return chat.type === ChatType.GROUP && chat.id === messageChatId || chat.type === ChatType.DIRECT && chat.last_message.conversation_id === messageChatId;
});
```
This will iterate over each chat in the chats array and run the provided function on that chat. If the function returns true on a particular chat, the find function will return that chat. If the find function iterates through the whole list and the function never returns true, then the find function will return undefined. Below, when we check `!chatOpen`, it will evaluate to `false` if `chatOpen` is `undefined`. Hope that makes sense.

2019-01-29 04:06 UTC, jamismoy commented on src/app/message-queue-module/store/message-queue.state.ts
> -        const chatOpen = chats.find(chat => chat.chat.id === messageChatId);
This has been changed in latest commit

2019-01-29 20:10 UTC, HolmanA commented on src/app/selected-chats-module/store/selected-chats.state.ts
> +        const channelId = directChat.last_message.conversation_id.replace('+' , '_');
No feedback here just want to comment on how annoying it is that GroupMe designed things in a way where we need this.... 😡

2019-02-01 07:07 UTC, jamismoy commented on src/app/selected-chats-module/store/selected-chats.state.ts
> +            messagePages = Array(selectedChat.messages[0].direct_messages);
To be honest I'm not sure exactly what is going on but selectedChat.messages[0].direct_messages
returns:

![image](https://user-images.githubusercontent.com/14933876/52107854-d6365b80-25ac-11e9-917d-02e6bf92fe5f.png)

while Array(selectedChat.messages[0].direct_messages) returns:

![image](https://user-images.githubusercontent.com/14933876/52107883-f6feb100-25ac-11e9-9157-7f6d605515e4.png)

2019-02-01 07:12 UTC, jamismoy commented on src/app/selected-chats-module/store/selected-chats.state.ts
> +            messagePages = Array(selectedChat.messages[0].direct_messages);
But selectedChat.messages[0] returns:

![image](https://user-images.githubusercontent.com/14933876/52108030-991e9900-25ad-11e9-8b01-27cb52738213.png)

which makes it seem like selectedChat.messages[0].direct_messages should return an array, but it doesnt... I am not sure whats going on

2019-02-01 07:14 UTC, jamismoy commented on src/app/selected-chats-module/store/selected-chats.state.ts
> +            messagePages = Array(selectedChat.messages[0].direct_messages);
And I've tried without explicity casting to an array and it does not work as it should

2019-02-01 07:21 UTC, jamismoy commented on src/app/selected-chats-module/store/selected-chats.state.ts
> +        const selectedChat = selectedChats[chatIndex];
addressed in latest commit

2019-02-01 07:22 UTC, jamismoy commented on src/app/selected-chats-module/store/selected-chats.state.ts
> +        let selectedChat;
addressed in latest commit

2019-02-01 07:22 UTC, jamismoy commented on src/app/selected-chats-module/store/selected-chats.state.ts
> +        let selectedChat;
addressed in latest commit

2019-02-25 03:05 UTC, HolmanA requested changes

2019-02-25 03:05 UTC, HolmanA commented on src/app/direct-chats-module/services/direct-chats.service.ts
> +            map(response => response.response),
You should call `response.response.reverse()` here (see the `fetchMessages` method in the `group-chats.service`). This way, the messages will be in the correct order when you insert the page into the array of message pages for this direct chat. This makes it so that you don't have to re-sort all message pages each time a new message arrives.

2019-02-25 03:05 UTC, HolmanA commented on src/app/ui-module/direct-messages/container/direct-messages.container.ts
> +        // @Select(SelectedChatsSelectors.getSelectedChatDetails(this.index)) chatDetails$: Observable<any>;
[NIT] I think these were some left-over comments that I forgot to delete that got copied over. Do you mind deleting them?

2019-02-25 03:34 UTC, HolmanA requested changes

2019-02-25 03:34 UTC, HolmanA commented on src/app/selected-chats-module/store/selected-chats.state.ts
> +            tap(messages => {
`fetchDirectChat` should return a single array of message objects. I think this is why you are having to wrap `direct_messages` in the `Array()` call all over the place. You should never have to access a message page via the `direct_messages` identifier if you are correctly mapping the response you get in the `fetchDirectChat` service method.

2019-02-25 03:34 UTC, HolmanA commented on src/app/selected-chats-module/store/selected-chats.state.ts
> +            tap(messages => {
In other words, the `messages` argument that you are providing this function should be a single array, with each element in the array being a single message object. Based on the screenshots you included when I asked about the `Array()` call, it looks like this `messages` argument is actually an object with the structure: 
<code>
{
   count: number,
   direct_messages: [],
   read_receipt: {}
}
</code>

2019-02-25 03:34 UTC, HolmanA commented on src/app/direct-chats-module/services/direct-chats.service.ts
> +            map(response => response.response),
Based on the object structure that I mentioned in my comment below, I think this should actually be something like `response.response.direct_messages.reverse()`. That will allow you to remove the Array() wrappers you have, the extra sorting, and most likely the conditionals you have in selected-chats.state.ts where you are having to check whether the selected chat is a group or direct before accessing the messages. My suggestions are spread out over several different comments so let me know if this is confusing.

2019-02-25 03:34 UTC, HolmanA commented on src/app/selected-chats-module/store/selected-chats.state.ts
> +            messagePages = Array(selectedChat.messages[0].direct_messages);
Here is an example of the conditional logic used to access a message page. When you fix the response mapping for direct messages, you should be able to remove this logic and access the `messagePages` via `selectedChat.messages` for both direct and group chats. There are a few more examples of this laying around, I'll let you track them down.

2019-03-21 02:51 UTC, HolmanA approved these changes
Great job man!!

2019-03-22 02:16 UTC, merged